import part

In [4]:
import numpy as np
import pandas as pd

Single-line loops (list comprehension)

In [5]:
newlist = [i if i%2 == 0 else 'Odd' for i in range(10)]
newlist

[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd']

In [6]:
x1 = [i/(5/3) for i in range(-5,6)]
print(x1)
print([ i**2 for i in x1 ])

[-3.0, -2.4, -1.7999999999999998, -1.2, -0.6, 0.0, 0.6, 1.2, 1.7999999999999998, 2.4, 3.0]
[9.0, 5.76, 3.2399999999999993, 1.44, 0.36, 0.0, 0.36, 1.44, 3.2399999999999993, 5.76, 9.0]


Broadcasting in numpy

In [14]:
v = [i for i in range(0,9)]
print(v)
print(' ')
M = np.reshape(v,(3,3))
print(M)
print(' ')
C = np.tile(M, (3,1))
print(C), print(' ')
B = C*np.reshape(v, (len(v),1))
print(B)
print(' ')

[0, 1, 2, 3, 4, 5, 6, 7, 8]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]
 
